#!/usr/bin/env python3
"""Generate investment thesis, valuation, and market expectation pages for the bank investment wiki."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List

VAULT_ROOT = Path(__file__).resolve().parent.parent
DATA_BASE = VAULT_ROOT / "02_原始资料" / "04_AkShare数据"
THESIS_DIR = VAULT_ROOT / "05_知识库" / "17_投资命题"
VAL_DIR = VAULT_ROOT / "05_知识库" / "18_估值"
EXPECT_DIR = VAULT_ROOT / "05_知识库" / "19_市场预期"

# Focus 18 banks with their core thesis and antithesis
FOCUS18_THESES = {
    "工商银行": {
        "core": "综合大行规模与系统重要性溢价",
        "antithesis": "资产增速放缓、净息差承压，规模溢价可能收缩",
        "peer": "国有大行",
        "key_driver": "资产规模全球领先，对公基建与政信客户粘性",
        "weak_link": "净息差下行周期中负债端弹性不足",
    },
    "建设银行": {
        "core": "基建与政信客户优势，资产质量稳健",
        "antithesis": "基建投资放缓可能压缩信贷需求与息差",
        "peer": "国有大行",
        "key_driver": "基建贷款传统优势，拨备覆盖充足",
        "weak_link": "地方化债对基建相关资产的传导路径",
    },
    "农业银行": {
        "core": "县域下沉护城河与三农金融不可替代性",
        "antithesis": "农村金融竞争加剧，息差收窄更甚",
        "peer": "国有大行",
        "key_driver": "网点覆盖最广，县域存款成本优势",
        "weak_link": "县域资产质量滞后暴露风险",
    },
    "中国银行": {
        "core": "国际化与外汇业务护城河",
        "antithesis": "海外息差下行与地缘风险对冲不足",
        "peer": "国有大行",
        "key_driver": "外汇业务传统优势，跨境人民币领先",
        "weak_link": "海外资产质量与地缘政治传导",
    },
    "邮储银行": {
        "core": "邮政网络渠道优势与零售存款护城河",
        "antithesis": "代理费模式成本刚性，资产端配置能力弱于同业",
        "peer": "国有大行",
        "key_driver": "网点数最多，零售存款占比最高",
        "weak_link": "代理费与资产端收益的剪刀差",
    },
    "交通银行": {
        "core": "长三角区域深耕与财富管理差异化",
        "antithesis": "大行中规模最小，缺乏显著护城河",
        "peer": "国有大行",
        "key_driver": "长三角经济腹地，财富管理转型",
        "weak_link": "规模与品牌相对弱势，同业夹击",
    },
    "招商银行": {
        "core": "零售银行与财富管理护城河",
        "antithesis": "零售竞争加剧与地产风险传导，AUM增长放缓",
        "peer": "股份行",
        "key_driver": "App月活领先，AUM与代销收入行业标杆",
        "weak_link": "房地产按揭与信用卡风险敞口",
    },
    "兴业银行": {
        "core": "金融市场与绿色金融能力领先",
        "antithesis": "同业业务监管趋严，绿色金融竞争加剧",
        "peer": "股份行",
        "key_driver": "同业与金融市场传统优势，绿色信贷领跑",
        "weak_link": "同业负债成本与监管收紧压力",
    },
    "平安银行": {
        "core": "平安集团综合金融协同",
        "antithesis": "集团协同天花板显现，零售风险周期性暴露",
        "peer": "股份行",
        "key_driver": "集团客户交叉引流，科技赋能零售",
        "weak_link": "消费贷与信用卡不良生成压力",
    },
    "中信银行": {
        "core": "对公与金融市场业务突出",
        "antithesis": "对公业务周期性强，零售转型缓慢",
        "peer": "股份行",
        "key_driver": "中信集团协同，对公客户资源丰富",
        "weak_link": "零售基础薄弱，息差弹性不足",
    },
    "浦发银行": {
        "core": "上海国资背景与对公业务基础",
        "antithesis": "资产质量历史包袱重，增长动力不足",
        "peer": "股份行",
        "key_driver": "长三角国资客户资源，对公业务规模",
        "weak_link": "历史不良消化与拨备消耗压力",
    },
    "民生银行": {
        "core": "股权分散下的市场化经营能力",
        "antithesis": "治理不确定性高，资产质量与息差承压",
        "peer": "股份行",
        "key_driver": "市场化机制，民营银行先发优势",
        "weak_link": "股权分散导致治理不稳定，战略摇摆",
    },
    "宁波银行": {
        "core": "长三角优质城商行，资产质量标杆",
        "antithesis": "估值溢价过高，息差收窄与异地扩张受限",
        "peer": "长三角城商行",
        "key_driver": "资产质量行业标杆，长三角深耕，风控文化",
        "weak_link": "高估值溢价隐含的预期差风险",
    },
    "江苏银行": {
        "core": "江苏省最大城商行，增长质量改善",
        "antithesis": "增速放缓与资产质量周期性暴露",
        "peer": "长三角城商行",
        "key_driver": "江苏经济腹地，规模与营收增速领先",
        "weak_link": "资产质量滞后暴露与区域集中度",
    },
    "成都银行": {
        "core": "成渝经济圈龙头，高增长与低不良",
        "antithesis": "区域经济周期性，增长天花板与资产质量滞后",
        "peer": "成渝城商行",
        "key_driver": "成渝双城经济圈龙头，基建与政信业务",
        "weak_link": "区域经济波动与地方平台敞口",
    },
    "杭州银行": {
        "core": "科创金融特色与杭州亚运城商行",
        "antithesis": "科创贷风险识别难度大，估值溢价高",
        "peer": "长三角城商行",
        "key_driver": "杭州数字经济腹地，科创金融先发优势",
        "weak_link": "科创贷风险滞后性与估值溢价风险",
    },
    "南京银行": {
        "core": "债券投资特色与长三角城商行多元收入",
        "antithesis": "债券投资波动性大，传统息差业务偏弱",
        "peer": "长三角城商行",
        "key_driver": "债券投资能力领先，非息收入占比高",
        "weak_link": "债券投资损益波动与利率风险",
    },
    "常熟银行": {
        "core": "小微金融标杆，下沉模式复制性",
        "antithesis": "下沉模式复制受限，息差收窄更甚",
        "peer": "长三角农商行",
        "key_driver": "小微贷款定价能力与风控技术",
        "weak_link": "异地扩张受限与下沉竞争加剧",
    },
}

# Industry-level theses
INDUSTRY_THESES = [
    {
        "name": "存款重定价推动净息差企稳",
        "claim": "存款利率下调的重定价效应将逐步传导至负债端，推动净息差在2026-2027年企稳",
        "scope": "行业",
        "applicable": "全部上市银行",
        "window": "年度/3年",
        "key_support": "2023-2025年多轮存款挂牌利率下调，定期存款重定价窗口逐步打开",
        "key_oppose": "资产端收益率同步下行，负债成本改善可能被资产端侵蚀",
        "verification": "行业NIM季度环比变化、存款成本率季度变化",
        "falsification": "若行业NIM连续4个季度环比下降且存款成本率未见改善，则命题削弱",
    },
    {
        "name": "地方化债降低城商行尾部风险",
        "claim": "地方政府化债政策将降低城商行对地方平台的风险敞口，改善资产质量预期",
        "scope": "行业",
        "applicable": "城商行，尤其成渝、西部、中部城商行",
        "window": "年度/3-5年",
        "key_support": "一揽子化债方案推进，城投债置换与展期减轻短期偿付压力",
        "key_oppose": "化债仅延后风险而非消除，长期仍需地方财政健康支撑",
        "verification": "城商行关注率、逾期率、地方平台贷款占比变化",
        "falsification": "若城商行关注率/逾期率连续上升且地方平台贷款质量恶化，则命题证伪",
    },
    {
        "name": "银行高股息可持续性",
        "claim": "国有大行和部分股份行的股息率在中长期具有可持续性，且估值修复将带来额外回报",
        "scope": "行业",
        "applicable": "国有大行、高股息股份行",
        "window": "3-5年",
        "key_support": "国有大行资本充足率较高、分红率稳定、监管鼓励分红",
        "key_oppose": "资本补充压力、利润增速放缓、息差收窄可能压缩分红空间",
        "verification": "核心一级资本充足率、分红率、利润增速",
        "falsification": "若核心一级资本充足率跌破监管底线或分红率连续下降，则命题证伪",
    },
    {
        "name": "零售银行分化加剧",
        "claim": "零售银行领域将出现显著分化，具备数字化能力和财富管理优势的银行将持续胜出",
        "scope": "行业",
        "applicable": "招商银行、平安银行、宁波银行等零售型银行",
        "window": "3-5年",
        "key_support": "财富管理市场规模扩大，数字化客户粘性增强",
        "key_oppose": "互联网平台竞争加剧，零售获客成本上升，按揭需求不足",
        "verification": "AUM增速、零售非息收入占比、App月活变化",
        "falsification": "若零售型银行AUM增速持续低于行业平均且获客成本持续上升，则命题证伪",
    },
]


def load_universe() -> List[Dict[str, Any]]:
    path = DATA_BASE / "数据字典与运行记录" / "a_share_banks_universe.json"
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data["banks"]


def generate_industry_thesis(thesis: Dict[str, Any]) -> str:
    name = thesis["name"]
    lines = [
        "---",
        f'title: "{name}"',
        "note_type: investment_thesis",
        "status: draft",
        "created: 2026-07-22",
        "updated: 2026-07-22",
        "data_cutoff: 2026-07-22",
        "report_period: NA",
        "evidence_level: medium",
        "evidence_class: research_inference",
        "source_priority: mixed",
        "sources:",
        "  - \"[[05_知识库/10_来源/来源_国家金融监督管理总局商业银行主要监管指标]]\"",
        "  - \"[[05_知识库/10_来源/来源_中国人民银行货币政策工具与利率政策]]\"",
        "related:",
        "  - \"[[05_知识库/11_研究框架/银行股完整投资研究框架]]\"",
        "  - \"[[05_知识库/02_行业主页/中国上市银行行业主页]]\"",
        "tags:",
        "  - 投资命题",
        "  - 行业",
        "  - 银行",
        "---",
        "",
        f"# {name}",
        "",
        f"> 用途：记录行业级投资命题，明确支持证据、反方论证、验证阈值和证伪条件。命题状态变化必须进入只追加日志。",
        "",
        "## 1. 命题定义",
        "",
        f"- 命题级别：行业",
        "- 命题状态：开放",
        f"- 核心主张：{thesis['claim']}",
        f"- 适用对象：{thesis['applicable']}",
        f"- 观察窗口：{thesis['window']}",
        "",
        "## 2. 支持证据",
        "",
        "| 证据 | 信息类别 | 证据等级 | 来源 | 对命题的作用 |",
        "| --- | --- | --- | --- | --- |",
        f"| {thesis['key_support']} | third_party_data / research_inference | medium | [[05_知识库/10_来源/来源_国家金融监督管理总局商业银行主要监管指标]] | 核心支持 |",
        "| 待补充更多量化证据 | — | — | — | — |",
        "",
        "## 3. 反对证据",
        "",
        "| 证据 | 信息类别 | 证据等级 | 来源 | 对命题的冲击 |",
        "| --- | --- | --- | --- | --- |",
        f"| {thesis['key_oppose']} | research_inference | low | — | 核心反驳 |",
        "| 待补充更多量化证据 | — | — | — | — |",
        "",
        "## 4. 市场当前预期",
        "",
        "> 本节专属 `external_expectation`。",
        "",
        "- 预期来源：待获取",
        "- 数据日期：NA",
        "- 预测期间：NA",
        "- 样本机构数量：NA",
        "- 市场当前主流预期：待获取",
        "- 与命题的关系：待评估",
        "",
        "## 5. 研究推断",
        "",
        f"- 为什么该命题可能成立：{thesis['key_support']}",
        f"- 命题的核心驱动：待深度研究",
        f"- 最脆弱的一环：{thesis['key_oppose']}",
        "- 若成立，对 ROE / 风险 / 资本 / 估值的影响：待量化",
        "",
        "## 6. 验证指标与阈值",
        "",
        "| 指标 | 当前值 | 阈值 | 时间窗口 | 来源 | 当前状态 |",
        "| --- | --- | --- | --- | --- | --- |",
        f"| {thesis['verification']} | 待验证 | 待设定 | {thesis['window']} | [[05_知识库/10_来源/来源_国家金融监督管理总局商业银行主要监管指标]] | 观察中 |",
        "",
        "## 7. 证伪条件",
        "",
        f"- 条件 1：{thesis['falsification']}",
        "- 条件 2：重大制度或监管变化使命题前提失效",
        "- 一旦满足条件后的动作：降级命题 / 调整估值 / 重写判断",
        "",
        "## 8. 盈利影响与估值影响",
        "",
        "### 盈利影响",
        "- 收入端：待量化",
        "- 成本端：待量化",
        "- 资产质量：待量化",
        "- 资本消耗：待量化",
        "",
        "### 估值影响",
        "- 影响估值框架：PB-ROE",
        "- 影响方向：待评估",
        "- 关键敏感参数：ROE / COE / g",
        "",
        "## 9. 关联与依赖命题",
        "",
        "- 上游命题：[[05_知识库/17_投资命题/存款重定价推动净息差企稳]]",
        "- 下游命题：各重点银行个股命题",
        "- 依赖的关键知识页：[[05_知识库/06_关键概念/NIM与净利差]]",
        "",
        "## 10. 待验证事项",
        "",
        "- [ ] 补充量化支持证据与数据来源",
        "- [ ] 设定验证指标的明确阈值",
        "- [ ] 获取市场一致预期数据",
        "",
        "## 11. 下一步",
        "",
        "- [ ] 补齐尚未建立的来源页双链",
        "- [ ] 在下一验证窗口更新指标、正反证据和命题状态",
        "- [ ] 若命题影响估值，联动更新对应估值页并记录参数变化",
        "",
        "## 12. 当前结论摘要",
        "",
        "- 当前判断：开放，证据不足",
        "- 下一次关键验证时点：2026Q1 财报",
        "",
        "## 13. 只追加更新日志",
        "",
        "- 2026-07-22 | 类型: 创建 | 状态: 开放 | 变更: 建立命题骨架 | 依据: [[06_维护契约]] | 影响: 待后续补证据",
    ]
    return "\n".join(lines)


def generate_bank_thesis(bank_name: str, info: Dict[str, str]) -> str:
    peer = info["peer"]
    lines = [
        "---",
        f'title: "{bank_name} 核心命题"',
        "note_type: investment_thesis",
        "status: draft",
        "created: 2026-07-22",
        "updated: 2026-07-22",
        "data_cutoff: 2026-07-22",
        "report_period: NA",
        "evidence_level: medium",
        "evidence_class: research_inference",
        "source_priority: company_filing",
        "sources:",
        f'  - "[[05_知识库/10_来源/{bank_name} 2025年年报]]"',
        f'  - "[[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]]"',
        "related:",
        f'  - "[[05_知识库/03_银行库/{bank_name} 深度研究]]"',
        f'  - "[[05_知识库/18_估值/{bank_name} 估值]]"',
        "tags:",
        "  - 投资命题",
        "  - 个股",
        f"  - {bank_name}",
        "---",
        "",
        f"# {bank_name} 核心命题",
        "",
        f"> 用途：记录{bank_name}个股级投资命题，明确支持证据、反方论证、验证阈值和证伪条件。",
        "",
        "## 1. 命题定义",
        "",
        "- 命题级别：个股",
        "- 命题状态：开放",
        f"- 核心主张：{info['core']}",
        f"- 适用对象：{bank_name}",
        "- 观察窗口：季度/年度/3-5年",
        "",
        "## 2. 支持证据",
        "",
        "| 证据 | 信息类别 | 证据等级 | 来源 | 对命题的作用 |",
        "| --- | --- | --- | --- | --- |",
        f"| {info['key_driver']} | official_fact / third_party_data | medium | [[05_知识库/10_来源/{bank_name} 2025年年报]] | 核心驱动 |",
        "| 待补充更多量化证据 | — | — | — | — |",
        "",
        "## 3. 反对证据",
        "",
        "| 证据 | 信息类别 | 证据等级 | 来源 | 对命题的冲击 |",
        "| --- | --- | --- | --- | --- |",
        f"| {info['antithesis']} | research_inference | low | — | 核心反驳 |",
        f"| {info['weak_link']} | research_inference | low | — | 最脆弱一环 |",
        "",
        "## 4. 市场当前预期",
        "",
        "> 本节专属 `external_expectation`。",
        "",
        "- 预期来源：待获取",
        "- 数据日期：NA",
        "- 预测期间：NA",
        "- 样本机构数量：NA",
        "- 市场当前主流预期：待获取",
        "- 与命题的关系：待评估",
        "",
        "## 5. 研究推断",
        "",
        f"- 为什么该命题可能成立：{info['key_driver']}",
        f"- 命题的核心驱动：{info['key_driver']}",
        f"- 最脆弱的一环：{info['weak_link']}",
        "- 若成立，对 ROE / 风险 / 资本 / 估值的影响：待量化",
        "",
        "## 6. 验证指标与阈值",
        "",
        "| 指标 | 当前值 | 阈值 | 时间窗口 | 来源 | 当前状态 |",
        "| --- | --- | --- | --- | --- | --- |",
        f"| ROE | 待验证 | 待设定 | 年度 | [[05_知识库/10_来源/{bank_name} 2025年年报]] | 观察中 |",
        f"| NIM | 待验证 | 待设定 | 季度 | [[05_知识库/10_来源/{bank_name} 2025年年报]] | 观察中 |",
        f"| 不良率 | 待验证 | 待设定 | 季度 | [[05_知识库/10_来源/{bank_name} 2025年年报]] | 观察中 |",
        f"| 核心一级资本充足率 | 待验证 | 待设定 | 季度 | [[05_知识库/10_来源/{bank_name} 2025年年报]] | 观察中 |",
        "",
        "## 7. 证伪条件",
        "",
        f"- 条件 1：{info['antithesis']}得到数据验证",
        "- 条件 2：核心财务指标连续2个季度低于阈值",
        "- 一旦满足条件后的动作：降级命题 / 调整估值 / 重写判断",
        "",
        "## 8. 盈利影响与估值影响",
        "",
        "### 盈利影响",
        "- 收入端：待量化",
        "- 成本端：待量化",
        "- 资产质量：待量化",
        "- 资本消耗：待量化",
        "",
        "### 估值影响",
        "- 影响估值框架：PB-ROE / RIM",
        "- 影响方向：待评估",
        "- 关键敏感参数：ROE / COE / g / 分红率",
        "",
        "## 9. 关联与依赖命题",
        "",
        "- 上游命题：[[05_知识库/17_投资命题/存款重定价推动净息差企稳]]",
        f"- 依赖的关键知识页：[[05_知识库/03_银行库/{bank_name}]]",
        "",
        "## 10. 待验证事项",
        "",
        "- [ ] 补充量化支持证据与数据来源",
        "- [ ] 设定验证指标的明确阈值",
        "- [ ] 获取市场一致预期数据",
        "",
        "## 11. 下一步",
        "",
        "- [ ] 补齐尚未建立的来源页双链",
        "- [ ] 在下一验证窗口更新指标、正反证据和命题状态",
        "- [ ] 若命题影响估值，联动更新对应估值页并记录参数变化",
        "",
        "## 12. 当前结论摘要",
        "",
        "- 当前判断：开放，证据不足",
        "- 下一次关键验证时点：2026Q1 财报",
        "",
        "## 13. 只追加更新日志",
        "",
        f"- 2026-07-22 | 类型: 创建 | 状态: 开放 | 变更: 建立命题骨架 | 依据: [[06_维护契约]] | 影响: 待后续补证据",
    ]
    return "\n".join(lines)


def generate_valuation_method() -> str:
    lines = [
        "---",
        "title: 银行估值方法体系",
        "note_type: knowledge_page",
        "status: draft",
        "created: 2026-07-22",
        "updated: 2026-07-22",
        "data_cutoff: 2026-07-22",
        "report_period: NA",
        "evidence_level: mixed",
        "evidence_class: mixed",
        "source_priority: mixed",
        "sources:",
        "  - \"[[06_维护契约]]\"",
        "  - \"[[06A_银行业数据口径规范]]\"",
        "related:",
        "  - \"[[05_知识库/11_研究框架/银行股完整投资研究框架]]\"",
        "  - \"[[05_知识库/06_关键概念/A-H银行股估值差异]]\"",
        "tags:",
        "  - 估值",
        "  - 方法论",
        "  - 银行",
        "---",
        "",
        "# 银行估值方法体系",
        "",
        "> 用途：建立统一的银行估值方法框架，明确各方法的适用范围、关键参数和信息类别隔离规则。所有估值参数都属于 `valuation_assumption`。",
        "",
        "## 1. PB-ROE 框架",
        "",
        "> 信息类别：`valuation_assumption`",
        "",
        "稳定期近似：",
        "",
        "```text",
        "P/B = (ROE - g) / (COE - g)",
        "```",
        "",
        "### 适用场景",
        "",
        "- 同业比较与估值分位",
        "- 解释估值溢价的来源",
        "- 反推隐含长期 ROE",
        "",
        "### 关键参数",
        "",
        "| 参数 | 含义 | 数据来源 | 信息类别 |",
        "| --- | --- | --- | --- |",
        "| ROE | 正常化净资产收益率 | 正式年报 / AkShare | official_fact / third_party_data |",
        "| COE | 股权成本率 | CAPM 或主观设定 | valuation_assumption |",
        "| g | 终值增长率 | 研究推断 | valuation_assumption |",
        "| BV | 每股净资产 | 正式年报 | official_fact |",
        "",
        "### 注意事项",
        "",
        "- 采用正常化 ROE，不直接外推单期 ROE",
        "- PB 必须同步标注所对应的账面净资产期末时点",
        "- A/H 银行需分别计算 PB",
        "",
        "## 2. RIM（剩余收益模型）",
        "",
        "> 信息类别：`valuation_assumption`",
        "",
        "```text",
        "V0 = BV0",
        "   + Sigma[(ROE_t - COE) x BV_(t-1) / (1 + COE)^t]",
        "   + 终值",
        "```",
        "",
        "### 适用场景",
        "",
        "- 主内在价值模型",
        "- 将银行价值拆为当前净资产和未来超额收益",
        "",
        "### 前提条件",
        "",
        "- 建模前必须评估账面资产是否充分确认潜在损失",
        "- 若账面净资产高估（如潜在不良未充分拨备），需先调整 BV0",
        "",
        "### 关键参数",
        "",
        "| 参数 | 含义 | 信息类别 |",
        "| --- | --- | --- |",
        "| BV0 | 当前每股净资产 | official_fact |",
        "| ROE_t | 预测期各年 ROE | valuation_assumption |",
        "| COE | 股权成本率 | valuation_assumption |",
        "| 终值增长率 | 长期稳定增长率 | valuation_assumption |",
        "",
        "## 3. DDM 与股息率",
        "",
        "> 信息类别：`valuation_assumption`",
        "",
        "```text",
        "P0 = D1 / (COE - g)",
        "```",
        "",
        "### 适用场景",
        "",
        "- 分红稳定、资本安全垫较高的成熟银行",
        "- 与国债、信用债、A/H 股息率和自身历史分位比较",
        "",
        "### 关键参数",
        "",
        "| 参数 | 含义 | 信息类别 |",
        "| --- | --- | --- |",
        "| D1 | 预期每股分红 | valuation_assumption |",
        "| COE | 股权成本率 | valuation_assumption |",
        "| g | 股息长期增长率 | valuation_assumption |",
        "",
        "## 4. PE 辅助",
        "",
        "> 仅用于阶段性盈利预期和历史区间交叉检查。拨备、信用成本及投资收益可能显著扭曲单期 PE。",
        "",
        "## 5. 三情景与回报拆解",
        "",
        "### 三情景设定",
        "",
        "每家重点银行设置悲观、基准和乐观情景，包含：",
        "",
        "- 资产增速",
        "- NIM",
        "- 非息增速",
        "- 信用成本",
        "- 正常化 ROE",
        "- 分红率",
        "- COE",
        "- 终值增长率",
        "",
        "### 3-5 年回报拆解",
        "",
        "```text",
        "3-5 年总回报",
        "  约等于 盈利与净资产增长",
        "  加上   股息回报",
        "  加上   估值变化",
        "  减去   资本补充摊薄",
        "```",
        "",
        "## 6. 估值隔离规则",
        "",
        "- 估值参数属于 `valuation_assumption`，不得写成公司已披露事实",
        "- 市场一致预期属于 `external_expectation`，不得写入估值假设",
        "- 正式披露的 PB/PE/股息率属于 `third_party_data` 或 `official_fact`",
        "- 情景分析结果由假设推导，必须标注假设来源",
        "",
        "## 7. 待验证事项",
        "",
        "- [ ] 各重点银行正常化 ROE 待研究后设定",
        "- [ ] COE 参数需统一口径（CAPM 或主观设定）",
        "- [ ] A/H 估值差异的合理解释范围待确定",
        "",
        "## 8. 只追加更新日志",
        "",
        "- 2026-07-22 | 类型: 创建 | 变更: 建立估值方法体系 | 依据: [[06_维护契约]] | 影响: 各银行估值页参数待设定",
    ]
    return "\n".join(lines)


def generate_bank_valuation(bank_name: str, info: Dict[str, str]) -> str:
    peer = info["peer"]
    lines = [
        "---",
        f'title: "{bank_name} 估值"',
        "note_type: valuation_page",
        "status: draft",
        "created: 2026-07-22",
        "updated: 2026-07-22",
        "data_cutoff: 2026-07-22",
        "report_period: NA",
        "evidence_level: medium",
        "evidence_class: valuation_assumption",
        "source_priority: mixed",
        "sources:",
        f'  - "[[05_知识库/10_来源/{bank_name} 2025年年报]]"',
        f'  - "[[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]]"',
        "related:",
        f'  - "[[05_知识库/03_银行库/{bank_name} 深度研究]]"',
        f'  - "[[05_知识库/17_投资命题/{bank_name} 核心命题]]"',
        "  - \"[[05_知识库/18_估值/银行估值方法体系]]\"",
        "tags:",
        "  - 估值",
        f"  - {bank_name}",
        "---",
        "",
        f"# {bank_name} 估值",
        "",
        f"> 用途：记录{bank_name}的估值假设、情景分析和预期回报。所有估值参数属于 `valuation_assumption`，不得写成公司已披露事实。",
        "",
        "## 1. 当前市场定价",
        "",
        "> 以下为 `third_party_data` 或 `official_fact`。",
        "",
        "| 指标 | 数值 | 数据日期 | 信息类别 | 证据等级 | 来源 |",
        "| --- | --- | --- | --- | --- | --- |",
        f"| PB | 待验证 | 2026-07-22 | third_party_data | medium | [[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]] |",
        f"| PE | 待验证 | 2026-07-22 | third_party_data | medium | [[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]] |",
        f"| 股息率 | 待验证 | 2026-07-22 | third_party_data | medium | [[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]] |",
        f"| 市值 | 待验证 | 2026-07-22 | third_party_data | medium | [[05_知识库/10_来源/AkShare {bank_name} 深度快照 2026-07-22]] |",
        "",
        "## 2. PB-ROE 分析",
        "",
        "> 本节为 `valuation_assumption`。",
        "",
        "| 参数 | 数值 | 信息类别 | 来源 |",
        "| --- | --- | --- | --- |",
        f"| 正常化 ROE | 待设定 | valuation_assumption | [[05_知识库/17_投资命题/{bank_name} 核心命题]] |",
        "| COE | 待设定 | valuation_assumption | CAPM / 主观设定 |",
        "| 终值增长率 g | 待设定 | valuation_assumption | — |",
        "| 隐含 PB | 待计算 | valuation_assumption | 由参数推导 |",
        "",
        f"同业比较组：{peer}",
        "",
        "## 3. RIM 内在价值",
        "",
        "> 本节为 `valuation_assumption`。",
        "",
        "| 参数 | 数值 | 信息类别 |",
        "| --- | --- | --- |",
        "| BV0 (每股净资产) | 待验证 | official_fact |",
        "| 预测期 ROE 路径 | 待设定 | valuation_assumption |",
        "| COE | 待设定 | valuation_assumption |",
        "| 终值增长率 | 待设定 | valuation_assumption |",
        "| 内在价值 | 待计算 | valuation_assumption |",
        "",
        "## 4. DDM 与股息率",
        "",
        "> 本节为 `valuation_assumption`。",
        "",
        "| 参数 | 数值 | 信息类别 |",
        "| --- | --- | --- |",
        "| 预期每股分红 D1 | 待设定 | valuation_assumption |",
        "| COE | 待设定 | valuation_assumption |",
        "| 股息增长率 g | 待设定 | valuation_assumption |",
        "| DDM 内在价值 | 待计算 | valuation_assumption |",
        "",
        "## 5. 三情景分析",
        "",
        "| 参数 | 悲观 | 基准 | 乐观 | 信息类别 |",
        "| --- | --- | --- | --- | --- |",
        "| 资产增速 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| NIM | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 非息增速 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 信用成本 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 正常化 ROE | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 分红率 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| COE | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 终值增长率 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 情景 PB | 待计算 | 待计算 | 待计算 | valuation_assumption |",
        "| 情景目标价 | 待计算 | 待计算 | 待计算 | valuation_assumption |",
        "",
        "## 6. 3-5 年回报拆解",
        "",
        "```text",
        "3-5 年总回报",
        "  约等于 盈利与净资产增长",
        "  加上   股息回报",
        "  加上   估值变化（PB 变化 x 净资产增长）",
        "  减去   资本补充摊薄",
        "```",
        "",
        "| 项目 | 悲观 | 基准 | 乐观 | 信息类别 |",
        "| --- | --- | --- | --- | --- |",
        "| 盈利与净资产增长 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 股息回报 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 估值变化 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 资本补充摊薄 | 待设定 | 待设定 | 待设定 | valuation_assumption |",
        "| 总回报 | 待计算 | 待计算 | 待计算 | valuation_assumption |",
        "",
        "## 7. 敏感性分析",
        "",
        "> 对关键参数进行敏感性测试。",
        "",
        "| ROE / COE | 低 COE | 基准 COE | 高 COE |",
        "| --- | --- | --- | --- |",
        "| 低 ROE | 待计算 | 待计算 | 待计算 |",
        "| 基准 ROE | 待计算 | 待计算 | 待计算 |",
        "| 高 ROE | 待计算 | 待计算 | 待计算 |",
        "",
        "## 8. 待验证事项",
        "",
        "- [ ] 正常化 ROE 需从深度研究中推导",
        "- [ ] COE 参数需统一设定",
        "- [ ] 三情景参数需根据行业和个股研究设定",
        "- [ ] A/H 估值差异需在估值页中分析",
        "",
        "## 9. 只追加更新日志",
        "",
        f"- 2026-07-22 | 类型: 创建 | 变更: 建立{bank_name}估值骨架 | 依据: [[06_维护契约]] | 影响: 参数待设定",
    ]
    return "\n".join(lines)


def generate_market_expectation(bank_name: str, info: Dict[str, str]) -> str:
    lines = [
        "---",
        f'title: "{bank_name} 市场预期"',
        "note_type: market_expectation",
        "status: draft",
        "created: 2026-07-22",
        "updated: 2026-07-22",
        "data_cutoff: 2026-07-22",
        "report_period: NA",
        "evidence_level: medium",
        "evidence_class: external_expectation",
        "source_priority: market_expectation",
        "sources:",
        "  - 待获取券商一致预期数据",
        "related:",
        f'  - "[[05_知识库/03_银行库/{bank_name} 深度研究]]"',
        f'  - "[[05_知识库/18_估值/{bank_name} 估值]]"',
        f'  - "[[05_知识库/17_投资命题/{bank_name} 核心命题]]"',
        "tags:",
        "  - 市场预期",
        f"  - {bank_name}",
        "---",
        "",
        f"# {bank_name} 市场预期",
        "",
        f"> 用途：独立记录{bank_name}的市场一致预期、券商预测和市场隐含预期。本页全部内容属于 `external_expectation`，与事实层严格隔离。",
        "",
        "## 1. 一致预期概览",
        "",
        "> 以下数据全部属于 `external_expectation`。",
        "",
        "| 项目 | 内容 |",
        "| --- | --- |",
        "| 预期来源 | 待获取 |",
        "| 数据日期 | NA |",
        "| 预测期间 | 2026E / 2027E |",
        "| 样本机构数量 | NA |",
        "",
        "## 2. 关键指标一致预期",
        "",
        "| 指标 | 2026E 一致预期 | 2027E 一致预期 | 与正式披露差异 | 可能滞后 |",
        "| --- | --- | --- | --- | --- |",
        "| 营业收入增速 | 待获取 | 待获取 | 待比较 | 待评估 |",
        "| 归母净利润增速 | 待获取 | 待获取 | 待比较 | 待评估 |",
        "| ROE | 待获取 | 待获取 | 待比较 | 待评估 |",
        "| NIM | 待获取 | 待获取 | 待比较 | 待评估 |",
        "| 不良率 | 待获取 | 待获取 | 待比较 | 待评估 |",
        "| 拨备覆盖率 | 待获取 | 待获取 | 待比较 | 待评估 |",
        "",
        "## 3. 券商目标价与评级",
        "",
        "| 机构 | 目标价 | 评级 | 日期 | 核心逻辑 |",
        "| --- | --- | --- | --- | --- |",
        "| 待获取 | — | — | — | — |",
        "",
        "## 4. 市场隐含预期",
        "",
        "> 从当前股价和 PB 反推市场隐含的长期 ROE 和增长率。",
        "",
        "| 项目 | 数值 | 信息类别 | 来源 |",
        "| --- | --- | --- | --- |",
        "| 当前 PB | 待验证 | third_party_data | AkShare |",
        "| 隐含长期 ROE | 待计算 | valuation_assumption | 由 PB/COE/g 反推 |",
        "| 隐含增长率 g | 待计算 | valuation_assumption | 由 PB/COE/ROE 反推 |",
        "",
        "## 5. 预期差分析",
        "",
        f"- 我们的推断 vs 一致预期：待研究",
        f"- 关联命题：[[05_知识库/17_投资命题/{bank_name} 核心命题]]",
        "- 预期差方向：待评估",
        "- 预期差大小：待评估",
        "",
        "## 6. 历史预期准确度",
        "",
        "> 记录一致预期与实际披露的偏差，用于评估滞后风险。",
        "",
        "| 期间 | 预期值 | 实际值 | 偏差 | 偏差原因 |",
        "| --- | --- | --- | --- | --- |",
        "| 待填充 | — | — | — | — |",
        "",
        "## 7. 待验证事项",
        "",
        "- [ ] 获取券商一致预期数据",
        "- [ ] 计算市场隐含 ROE 和增长率",
        "- [ ] 对比我们的推断与一致预期",
        "",
        "## 8. 只追加更新日志",
        "",
        f"- 2026-07-22 | 类型: 创建 | 变更: 建立{bank_name}市场预期骨架 | 依据: [[06_维护契约]] | 影响: 待获取数据",
    ]
    return "\n".join(lines)


def main() -> int:
    print("Loading bank universe...")
    banks = load_universe()
    focus_banks = [b for b in banks if b.get("focus18")]

    # Ensure directories exist
    THESIS_DIR.mkdir(parents=True, exist_ok=True)
    VAL_DIR.mkdir(parents=True, exist_ok=True)
    EXPECT_DIR.mkdir(parents=True, exist_ok=True)

    # Generate industry theses
    ind_count = 0
    for thesis in INDUSTRY_THESES:
        content = generate_industry_thesis(thesis)
        path = THESIS_DIR / f"{thesis['name']}.md"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        ind_count += 1
    print(f"Created {ind_count} industry thesis pages")

    # Generate bank-level theses
    bank_thesis_count = 0
    for bank in focus_banks:
        name = bank["name"]
        if name not in FOCUS18_THESES:
            print(f"  Warning: no thesis defined for {name}, using generic template")
            info = {
                "core": "待深度研究后填充",
                "antithesis": "待深度研究后填充",
                "peer": "待设定",
                "key_driver": "待深度研究后填充",
                "weak_link": "待深度研究后填充",
            }
        else:
            info = FOCUS18_THESES[name]
        content = generate_bank_thesis(name, info)
        path = THESIS_DIR / f"{name} 核心命题.md"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        bank_thesis_count += 1
    print(f"Created {bank_thesis_count} bank thesis pages")

    # Generate valuation method page
    val_method_content = generate_valuation_method()
    val_method_path = VAL_DIR / "银行估值方法体系.md"
    with open(val_method_path, "w", encoding="utf-8") as f:
        f.write(val_method_content)
    print("Created 1 valuation method page")

    # Generate bank valuation pages
    bank_val_count = 0
    for bank in focus_banks:
        name = bank["name"]
        if name not in FOCUS18_THESES:
            info = {
                "core": "待深度研究后填充",
                "antithesis": "待深度研究后填充",
                "peer": "待设定",
                "key_driver": "待深度研究后填充",
                "weak_link": "待深度研究后填充",
            }
        else:
            info = FOCUS18_THESES[name]
        content = generate_bank_valuation(name, info)
        path = VAL_DIR / f"{name} 估值.md"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        bank_val_count += 1
    print(f"Created {bank_val_count} bank valuation pages")

    # Generate market expectation pages
    expect_count = 0
    for bank in focus_banks:
        name = bank["name"]
        if name not in FOCUS18_THESES:
            info = {
                "core": "待深度研究后填充",
                "antithesis": "待深度研究后填充",
                "peer": "待设定",
                "key_driver": "待深度研究后填充",
                "weak_link": "待深度研究后填充",
            }
        else:
            info = FOCUS18_THESES[name]
        content = generate_market_expectation(name, info)
        path = EXPECT_DIR / f"{name} 市场预期.md"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        expect_count += 1
    print(f"Created {expect_count} market expectation pages")

    total = ind_count + bank_thesis_count + 1 + bank_val_count + expect_count
    print(f"\nTotal: {ind_count} industry theses + {bank_thesis_count} bank theses + 1 valuation method + {bank_val_count} bank valuations + {expect_count} market expectations = {total} files")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
